### ISSUE TITLE
Empty list

### ISSUE THREAD

**Issue by averrin** [carloshfoliveira/project-switcher#9]
Just press ctrl+;

**Atom Version**: 1.7.0-beta1
**System**: KDE neon
**Thrown From**: [project-switcher2](https://github.com/chocoelho/project-switcher2) package, v1.2.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/home/user/projects/monitoring,/home/user/projects'

```
At fs.js:856

Error: ENOENT: no such file or directory, scandir '/home/user/projects/monitoring,/home/user/projects'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at Object.exports.readProjects (/home/user/.atom/packages/project-switcher2/lib/utils.coffee:19:14)
    at Object.exports.getSiblingProjects (/home/user/.atom/packages/project-switcher2/lib/utils.coffee:12:18)
    at Object.exports.listProjects (/home/user/.atom/packages/project-switcher2/lib/utils.coffee:8:13)
    at ProjectSwitcher2View.module.exports.ProjectSwitcher2View.show (/home/user/.atom/packages/project-switcher2/lib/project-switcher2-view.coffee:43:19)
    at ProjectSwitcher2View.module.exports.ProjectSwitcher2View.toggle (/home/user/.atom/packages/project-switcher2/lib/project-switcher2-view.coffee:52:8)
    at atom-workspace.<anonymous> (/home/user/.atom/packages/project-switcher2/lib/project-switcher2-view.coffee:11:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:18.5.0 grammar-selector:show (atom-text-editor.editor.vim-mode-plus.normal-mode)
  2x -4:18.4.0 blur (a.inline-block)
     -4:03.8.0 grammar-selector:show (atom-text-editor.editor.vim-mode-plus.normal-mode)
  4x -4:03.8.0 blur (a.inline-block)
     -0:53 settings-view:open (a.inline-block)
 10x -0:52.7.0 blur (a.inline-block)
     -0:41.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:36.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:24.4.0 emmet:encode-decode-data-url (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-base16-tomorrow-dark-theme.theme-accents-ui)
     -0:21.8.0 project-switcher2:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-base16-tomorrow-dark-theme.theme-accents-ui)
     -0:18.5.0 emmet:encode-decode-data-url (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-base16-tomorrow-dark-theme.theme-accents-ui)
  4x -0:15.3.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel.ignore-hidden)
     -0:11.4.0 key-binding-resolver:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:09.2.0 emmet:encode-decode-data-url (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:01.6.0 project-switcher2:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "web-browser",
      "tool-bar-main",
      "spell-check",
      "seti-icons",
      "atom-color-highlight",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "deprecation-cop",
      "symbols-view",
      "symbols-tree-view",
      "vim-mode",
      "color-tabs-regex",
      "vim-shift-movers",
      "about",
      "archive-view",
      "autoflow",
      "dev-live-reload",
      "encoding-selector",
      "language-c",
      "language-make",
      "language-objective-c",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "link",
      "styleguide",
      "tidy-tabs",
      "tab-to-escape",
      "godef",
      "linter-golinter",
      "glow",
      "go-debug"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
MagicPython, v0.5.8
accents-ui, v1.2.0
api-docs, vundefined
atom-beautify, v0.28.28
atom-ctags, v4.5.2
atom-hide-tabs, v0.2.1
atom-jinja2, v0.5.0
atomic-sync, v0.6.4
autocomplete-go, v1.0.5
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
build, v0.58.0
build-gulp, v0.7.0
builder-go, v1.0.0
close-other-tabs, v0.1.0
color-picker, v2.1.1
colorful-cursor, v0.3.1
editorconfig, v1.2.4
emmet, v2.4.3
environment, v1.2.0
file-icons, v1.6.19
git-hide, v0.1.2
go-config, v1.1.2
go-find-references, v1.2.3
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
javascript-snippets, v1.2.1
language-babel, v2.16.0
language-diff, v0.4.0
language-lua, v0.9.4
linter, v1.11.4
linter-eslint, v7.1.3
linter-govet, v0.1.5
linter-jscs, v3.4.10
linter-jshint, v2.0.3
linter-pep8, v1.2.1
linter-pylama, v0.2.9
minimap, v4.21.0
minimap-bookmarks, v0.3.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
navigator-godef, v1.0.2
nerd-treeview, v0.4.2
pigments, v0.26.0
project-switcher2, v1.2.0
python-tools, v0.6.7
remember-file-positions, v0.2.2
swackets, v0.10.0
sync-settings, v0.7.2
tester-go, v1.0.3
time-status, v1.1.2
underline-trailing-whitespace, v1.4.0
vim-mode-plus, v0.28.0
vim-mode-plus-move-to-symbols, v0.1.4
vim-mode-plus-subword-movement, v0.2.2
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by chocoelho** [comment]
hmmm, I see there's a problem with multiple folders. I'll make a patch 
for it. Did you check the project home box?

**Comment by chocoelho** [comment]
There's still a problem when using multiple folders. I see you have 
defined two folders for projects. I'm working on a fix for that.

**Comment by chocoelho** [comment]
New minor release is available :) Please update.

**Comment by chocoelho** [comment]
Did it work?

**Comment by averrin** [comment]
I  will test it today

**Comment by averrin** [comment]
It works, thx!
